enum sdkResponse{
  SUCCESS_WSQ_EXPORT,
  CANCELLATION,
  SCANNING_FAILURE,
  SCANNING_ERROR,
  LICENSE_FAILED,
  INITIALIZATION_EXCEPTION,
  NO_CAMERA,
  NO_AUTO_FOCUS,
  NO_FLASH_LIGHT,
  CAMERA_PERMISSION_REQUIRED
}